#  1 apt addons                    // apt-get install
#  2 cache components              // what to cache
#  3 before_install                // before installing components for VM based on profile
#  4 install                       // installing components for VM based on profile
## 5 jobs ###
#  6 before_script                 // before shell scripting
#  7 script                        // run as shell scripting
#  8 before_cache                  // before saving cache
#  9 after_success / after_failure // after exit code 0/non-zero
# 10 before_deploy                 // if deploying, before deployment
# 11 deploy                        // if deploying, deployment
# 12 after_deploy                  // if deploying, after deployment
# 13 after_script                  // end step

# Bionic 3.7 / Global
# Globe:      1, 2     4, 5
# Tests:                     6, 7
# Build:            3,          7,    9, 10, 11
# Tests:      1, 2,    4, 5, 6, 7
# Build:      1, 2, 3, 4, 5,    7,    9, 10, 11
# Build: 3: get pcregrep
# Globe: 4: get pip; DEPLOY=yes; DEPLOY_PAGES=no
# Globe: 5: Define Tests/Build-Deploy
# Tests: 7: run tests.py
# Build: 7: get upx; run build.py (create binary)
# Build: 9: set git tag to version number
#           if windows, set to deploy GHPages; DEPLOY_PAGES=yes
#           prepare for GHReleases
# Build:10: set vars for:
#           git tag
#           release name
#           files for GHReleases
#           files for GHPages
#           if using CLI Releaser, set up that stuff
#           print debug info for deployment
# Build:11: deploy to:
#           GitHub Releases
#             make new release
#             repo:      Artheau/SpriteSomething
#             condition: $DEPLOY == "yes"
#             branch:    master
#           GitHub Pages
#             upload new pages site
#              remember to upload EVERYTHING as this will nuke what's there
#             repo:      Artheau/SpriteSomething
#             condition: $DEPLOY_PAGES == "yes"
#             branch:    master

# Xenial 3.7
# Build: 6: DEPLOY=no

# Xenial 3.6
# Build: 6: DEPLOY=no

# OSX 10.14
# Tests: 3: use python3; don't need pcregrep
# Build: 3: use python3; don't need pcregrep

# Win10v1803
# Tests: 3: get python
#           export path
#           get pip
#           get more stuff for windows
#           don't need pcregrep, using py clone
# Build: 3: get python
#           export path
#           get pip
#           get more stuff for windows
#           don't need pcregrep, using py clone
# Build: 6: DEPLOY_PAGES=yes
